version: "3"
services:
  app:
    build:
      context: .
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8070:8080"
